### ISSUE TITLE
Update Hapi plugin usage of server logging

### ISSUE THREAD

**Issue by cadecairos** [nlf/bucker#42]
Hapi 8.4.0 (or earlier) deprecated `server.events`

Using `server.on` will fix compatibility.

**Comment by cadecairos** [comment]
that was fast! :+1: Thanks :D

**Comment by nlf** [comment]
not really, i've been sitting on a fix for it for quite a while now. a second one coming in made me feel guilty and spurred me into action lol. thanks for helping keep things alive!
